import { getSingleProperty } from "@/store/data";
import { PropertyData } from "@/types/types";
import { useState, useEffect } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import { useToast } from "@/hooks/use-toast";
import { previewAoa, sendAoaForClient } from "@/api/api";
import { ContractPreviewAndSend } from "@/components/portal/shared/ContractPreviewAndSend";
import { routes } from "@/routes/ROUTES";

export default function PropertyAoaPage() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const propertyIdParam = searchParams.get("propertyId");
  const { toast } = useToast();
  const [isSending, setIsSending] = useState(false);
  const [propertyData, setPropertyData] = useState<PropertyData | null>(null);
  const [aoaPdfBase64, setAoaPdfBase64] = useState<string | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);

  useEffect(() => {
    const fetchPropertyData = async () => {
      try {
        if (propertyIdParam) {
          const response = await getSingleProperty({
            propertyId: propertyIdParam,
          });
          setPropertyData(response ?? null);
        } else {
          setPropertyData(null);
        }
      } catch (error) {
        console.error("Error fetching property data:", error);
        setPropertyData(null);
      }
    };
    if (propertyIdParam) fetchPropertyData();
  }, [propertyIdParam]);

  const clientIdNum = propertyData?.client?.id;
  const propertyIdNum = propertyData?.propertyDetails?.id;

  useEffect(() => {
    if (clientIdNum == null || propertyIdNum == null) return;
    setPreviewLoading(true);
    setPreviewError(null);
    previewAoa(clientIdNum, propertyIdNum)
      .then((res) => {
        setAoaPdfBase64(res.aoaPdf ?? null);
      })
      .catch((err) => {
        setPreviewError(
          err instanceof Error ? err.message : "Failed to load AOA preview"
        );
      })
      .finally(() => setPreviewLoading(false));
  }, [clientIdNum, propertyIdNum]);

  const handleDownloadPdf = () => {
    if (!aoaPdfBase64) return;
    try {
      const blob = new Blob(
        [Uint8Array.from(atob(aoaPdfBase64), (c) => c.charCodeAt(0))],
        { type: "application/pdf" }
      );
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `aoa-property-${propertyData?.propertyDetails?.accountNumber ?? propertyIdParam ?? "aoa"}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast({
        title: "Download started",
        description: "AOA PDF has been downloaded.",
      });
    } catch {
      toast({
        title: "Download failed",
        description: "Could not save the PDF.",
        variant: "destructive",
      });
    }
  };

  const handleSendAoa = async () => {
    if (clientIdNum == null || propertyIdNum == null) {
      toast({
        title: "Error",
        description: "Property data not loaded or missing client/property ID.",
        variant: "destructive",
      });
      return;
    }
    setIsSending(true);
    try {
      await sendAoaForClient(clientIdNum, propertyIdNum);
      toast({
        title: "✓ AOA sent for signing",
        description:
          "AOA has been sent to the client. They will receive an email from DocuSign.",
      });
      navigate(routes.properties.view(propertyIdNum));
    } catch (error) {
      toast({
        title: "Failed to send AOA",
        description:
          error instanceof Error ? error.message : "Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSending(false);
    }
  };

  return (
    <ContractPreviewAndSend
      pdfBase64={aoaPdfBase64}
      loading={previewLoading}
      error={previewError}
      onDownload={handleDownloadPdf}
      onSend={handleSendAoa}
      isSending={isSending}
      sendDisabled={clientIdNum == null || propertyIdNum == null}
      title="AOA (Appointment of Agent — generated by server)"
      hasEntity={!!propertyIdParam}
      emptyMessage={
        <p>
          Open this page with a property selected (e.g. from Property details →
          Create AOA) to load the AOA.
        </p>
      }
    />
  );
}
