import { getSingleClient } from "@/store/data";
import { ClientData, Property } from "@/types/types";
import { useState, useEffect } from "react";
import { useSearchParams, useNavigate } from "react-router-dom";
import { useToast } from "@/hooks/use-toast";
import { previewContract, sendContractForClient } from "@/api/api";
import { ContractPreviewAndSend } from "@/components/portal/shared/ContractPreviewAndSend";
import { routes } from "@/routes/ROUTES";

interface Client {
  client: ClientData;
  properties: Property[];
}

export default function ContractForm() {
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const clientId = searchParams.get("clientId");
  const { toast } = useToast();
  const [isSending, setIsSending] = useState(false);
  const [clientData, setClientData] = useState<Client>();
  const [contractPdfBase64, setContractPdfBase64] = useState<string | null>(null);
  const [previewLoading, setPreviewLoading] = useState(false);
  const [previewError, setPreviewError] = useState<string | null>(null);

  useEffect(() => {
    const fetchClientData = async () => {
      try {
        if (clientId) {
          const response = await getSingleClient({ clientId });
          setClientData(response);
        }
      } catch (error) {
        console.error("Error fetching client data:", error);
      }
    };
    if (clientId) fetchClientData();
  }, [clientId]);

  useEffect(() => {
    if (!clientData?.client?.id) return;
    setPreviewLoading(true);
    setPreviewError(null);
    previewContract(clientData.client.id)
      .then((res) => {
        setContractPdfBase64(res.contractPdf ?? null);
      })
      .catch((err) => {
        setPreviewError(err instanceof Error ? err.message : "Failed to load preview");
      })
      .finally(() => setPreviewLoading(false));
  }, [clientData?.client?.id]);

  const handleDownloadPdf = () => {
    if (!contractPdfBase64) return;
    try {
      const blob = new Blob(
        [Uint8Array.from(atob(contractPdfBase64), (c) => c.charCodeAt(0))],
        { type: "application/pdf" }
      );
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `contract-client-${clientData?.client?.clientNumber ?? clientId ?? "contract"}.pdf`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast({
        title: "Download started",
        description: "Contract PDF has been downloaded.",
      });
    } catch {
      toast({
        title: "Download failed",
        description: "Could not save the PDF.",
        variant: "destructive",
      });
    }
  };

  const handleSendContract = async () => {
    if (!clientData?.client?.id) {
      toast({
        title: "Error",
        description: "Client data not loaded or missing client ID.",
        variant: "destructive",
      });
      return;
    }
    setIsSending(true);
    try {
      await sendContractForClient(clientData.client.id);
      toast({
        title: "✓ Contract sent for signing",
        description: "Contract has been sent to the client. They will receive an email from DocuSign.",
      });
      navigate(routes.client.detail(clientData.client.id));
    } catch (error) {
      toast({
        title: "Failed to send contract",
        description: error instanceof Error ? error.message : "Please try again.",
        variant: "destructive",
      });
    } finally {
      setIsSending(false);
    }
  };

  return (
    <ContractPreviewAndSend
      pdfBase64={contractPdfBase64}
      loading={previewLoading}
      error={previewError}
      onDownload={handleDownloadPdf}
      onSend={handleSendContract}
      isSending={isSending}
      sendDisabled={!clientData?.client?.id}
      title="Contract (generated by server)"
      hasEntity={!!clientId}
      emptyMessage={
        <p>
          Open this page with a client selected (e.g. from Client details → Create Contract) to load the contract.
        </p>
      }
    />
  );
}
