import { Button } from "@/components/ui/button";
import { LoaderCircle, Download, Send } from "lucide-react";

export interface ContractPreviewAndSendProps {
  /** Base64 PDF string from server */
  pdfBase64: string | null;
  loading: boolean;
  error: string | null;
  onDownload: () => void;
  onSend: () => void;
  isSending: boolean;
  sendDisabled?: boolean;
  /** Label for the PDF section (e.g. "Contract (generated by server)") */
  title?: string;
  /** Message when no entity id (e.g. "Open with a client selected...") */
  emptyMessage?: React.ReactNode;
  /** Only show content when we have an entity (e.g. clientId or prospect id) */
  hasEntity: boolean;
}

export function ContractPreviewAndSend({
  pdfBase64,
  loading,
  error,
  onDownload,
  onSend,
  isSending,
  sendDisabled = false,
  title = "Contract (generated by server)",
  emptyMessage,
  hasEntity,
}: ContractPreviewAndSendProps) {
  const hasPdf = !!pdfBase64 && !loading;

  return (
    <div className="p-4 max-w-4xl mx-auto">
      <div className="flex flex-wrap gap-2 mb-4">
        <Button
          variant="default"
          className="rounded-md p-2 px-6 bg-brand-blue hover:bg-brand-blue-hover text-white"
          onClick={onDownload}
          disabled={!hasPdf}
        >
          <Download className="mr-2 h-4 w-4" />
          Download PDF
        </Button>
        <Button
          variant="default"
          className="rounded-md p-2 px-6 bg-brand-blue hover:bg-brand-blue-hover text-white"
          onClick={onSend}
          disabled={sendDisabled || isSending || !hasPdf}
        >
          {isSending ? (
            <span className="flex items-center gap-2">
              <LoaderCircle className="animate-spin h-5 w-5" />
              Sending...
            </span>
          ) : (
            <>
              <Send className="mr-2 h-4 w-4" />
              Send for signing
            </>
          )}
        </Button>
      </div>

      {loading && (
        <div className="flex items-center justify-center py-12 gap-2 text-gray-600">
          <LoaderCircle className="h-6 w-6 animate-spin" />
          Loading contract from server...
        </div>
      )}

      {error && (
        <div className="rounded-lg border border-amber-200 bg-amber-50 p-4 text-amber-800 mb-4">
          <p className="font-medium">Preview could not be loaded</p>
          <p className="text-sm mt-1">{error}</p>
        </div>
      )}

      {hasPdf && (
        <div className="rounded-lg border bg-white overflow-hidden">
          <p className="text-sm font-medium text-gray-700 p-2 border-b bg-gray-50">
            {title}
          </p>
          <iframe
            title="Contract preview"
            src={`data:application/pdf;base64,${pdfBase64}#toolbar=0&navpanes=0`}
            className="w-full h-[75vh] min-h-[500px]"
          />
        </div>
      )}

      {!hasEntity && emptyMessage && (
        <div className="rounded-lg border border-gray-200 bg-gray-50 p-4 text-gray-600">
          {emptyMessage}
        </div>
      )}
    </div>
  );
}
