-- CreateTable
CREATE TABLE "CsvTable" (
    "id" SERIAL NOT NULL,
    "StatusNotes" TEXT,
    "OtherNotes" TEXT,
    "TypeOfAcct" TEXT,
    "CLIENTNumber" TEXT,
    "CLIENTNAME" TEXT,
    "NAMEONCAD" TEXT,
    "MAILINGADDRESS" TEXT,
    "MAILINGADDRESSCITYTXZIP" TEXT,
    "CADMailingADDRESS" TEXT,
    "CADCITY" TEXT,
    "CADZIPCODE" TEXT,
    "PHONENUMBER" TEXT,
    "Email" TEXT,
    "CADCOUNTY" TEXT,
    "AccountNumber" TEXT,
    "CONTACTOWNER" TEXT,
    "SUBCONTRACTOWNER" TEXT,
    "BPPFEE" TEXT,
    "CONTINGENCYFee" TEXT,
    "FlatFee" TEXT,
    "BPPInvoice" TEXT,
    "BPPInvoicePaid" TEXT,
    "NoticeMarketValue" TEXT,
    "FinalMarketValue" TEXT,
    "MarketValueReduction" TEXT,
    "NoticeAppraisedValue" TEXT,
    "FinalAppraisedValue" TEXT,
    "ValueAppraisedValueReduction" TEXT,
    "ValueOverallTaxRate" TEXT,
    "ValueTaxSavings" TEXT,
    "Contingency" TEXT,
    "ContingencyFeeDue" TEXT,
    "TaxBPPBPPLastYearAppraised" TEXT,
    "TaxBPPFinalAppraisedTotal" TEXT,
    "TaxBPPAppraisedValueReduction" TEXT,
    "TaxBPPOverallTaxRate" TEXT,
    "TaxBPPTaxSavings" TEXT,
    "TaxBPPContingencyFee" TEXT,
    "TaxBPPDue" TEXT,
    "JustBPPBPPLastYearAppraised" TEXT,
    "BPPThisYearAppraised" TEXT,
    "ProtestInvoice" TEXT,
    "ProtestInvoicePaid" TEXT,
    "ONLYMarketChangeInARB" TEXT,
    "NoticeAppraisedTotal" TEXT,
    "ArbitrationFinalAppraisedTotal" TEXT,
    "ArbitrationAppraisedValueReduction" TEXT,
    "ArbitrationOverallTaxRate" TEXT,
    "TaxSavings" TEXT,
    "ArbitrationContingencyFee" TEXT,
    "ArbitrationDue" TEXT,
    "ARBFee" TEXT,
    "ComptrollerRefundCK" TEXT,
    "CollectOrRefund" TEXT,
    "ARBInvoice" TEXT,
    "ClientPaidOrArbRefundUsed" TEXT,
    "TotalDue" TEXT,
    "TypeOfService" TEXT,
    "AnyRandamServiceInvoice" TEXT,
    "RandomServiceFeeInvoicePaid" TEXT,
    "LastYearAppraised" TEXT,
    "Value2525FinalAppraisedTotal" TEXT,
    "Value2525AppraisedValueReduction" TEXT,
    "Value2525OverallTaxRate" TEXT,
    "Value2525TaxSavings" TEXT,
    "Value2525ContingencyFee" TEXT,
    "Value2525Due" TEXT,
    "PastDue" TEXT,
    "PastDuePaid" TEXT,
    "IsArchived" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "CsvTable_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Client" (
    "id" SERIAL NOT NULL,
    "TypeOfAcct" TEXT,
    "CLIENTNumber" TEXT,
    "CLIENTNAME" TEXT,
    "Email" TEXT,
    "PHONENUMBER" TEXT,
    "NAMEONCAD" TEXT,
    "MAILINGADDRESS" TEXT,
    "MAILINGADDRESSCITYTXZIP" TEXT,
    "IsArchived" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Client_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Property" (
    "id" SERIAL NOT NULL,
    "StatusNotes" TEXT,
    "OtherNotes" TEXT,
    "NAMEONCAD" TEXT,
    "MAILINGADDRESS" TEXT,
    "MAILINGADDRESSCITYTXZIP" TEXT,
    "CADMailingADDRESS" TEXT,
    "CADCITY" TEXT,
    "CADZIPCODE" TEXT,
    "CADCOUNTY" TEXT,
    "AccountNumber" TEXT,
    "CLIENTNumber" TEXT,
    "CONTACTOWNER" TEXT,
    "SUBCONTRACTOWNER" TEXT,
    "BPPFEE" TEXT,
    "CONTINGENCYFee" TEXT,
    "FlatFee" TEXT,
    "IsArchived" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Property_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Invoice" (
    "id" SERIAL NOT NULL,
    "AccountNumber" TEXT,
    "CLIENTNumber" TEXT,
    "BPPInvoice" TEXT,
    "BPPInvoicePaid" TEXT,
    "NoticeMarketValue" TEXT,
    "FinalMarketValue" TEXT,
    "MarketValueReduction" TEXT,
    "NoticeAppraisedValue" TEXT,
    "FinalAppraisedValue" TEXT,
    "ValueAppraisedValueReduction" TEXT,
    "ValueOverallTaxRate" TEXT,
    "ValueTaxSavings" TEXT,
    "Contingency" TEXT,
    "ContingencyFeeDue" TEXT,
    "TaxBPPBPPLastYearAppraised" TEXT,
    "TaxBPPFinalAppraisedTotal" TEXT,
    "TaxBPPAppraisedValueReduction" TEXT,
    "TaxBPPOverallTaxRate" TEXT,
    "TaxBPPTaxSavings" TEXT,
    "TaxBPPContingencyFee" TEXT,
    "TaxBPPDue" TEXT,
    "JustBPPBPPLastYearAppraised" TEXT,
    "BPPThisYearAppraised" TEXT,
    "ProtestInvoice" TEXT,
    "ProtestInvoicePaid" TEXT,
    "ONLYMarketChangeInARB" TEXT,
    "NoticeAppraisedTotal" TEXT,
    "ArbitrationFinalAppraisedTotal" TEXT,
    "ArbitrationAppraisedValueReduction" TEXT,
    "ArbitrationOverallTaxRate" TEXT,
    "TaxSavings" TEXT,
    "ArbitrationContingencyFee" TEXT,
    "ArbitrationDue" TEXT,
    "ARBFee" TEXT,
    "ComptrollerRefundCK" TEXT,
    "CollectOrRefund" TEXT,
    "ARBInvoice" TEXT,
    "ClientPaidOrArbRefundUsed" TEXT,
    "TotalDue" TEXT,
    "TypeOfService" TEXT,
    "AnyRandamServiceInvoice" TEXT,
    "RandomServiceFeeInvoicePaid" TEXT,
    "LastYearAppraised" TEXT,
    "Value2525FinalAppraisedTotal" TEXT,
    "Value2525AppraisedValueReduction" TEXT,
    "Value2525OverallTaxRate" TEXT,
    "Value2525TaxSavings" TEXT,
    "Value2525ContingencyFee" TEXT,
    "Value2525Due" TEXT,
    "PastDue" TEXT,
    "PastDuePaid" TEXT,
    "IsArchived" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Invoice_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "User" (
    "id" SERIAL NOT NULL,
    "email" TEXT NOT NULL,
    "password" TEXT NOT NULL,
    "type" TEXT NOT NULL DEFAULT 'client',
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "User_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Client_CLIENTNumber_key" ON "Client"("CLIENTNumber");

-- CreateIndex
CREATE UNIQUE INDEX "User_email_key" ON "User"("email");
